spring.application.name=SmartBioBackend

# H2 in-memory database mens vi udvikler
spring.datasource.url=jdbc:h2:mem:smartbio
spring.h2.console.enabled=true

# Kør data.sql efter at tabellerne er oprettet
spring.jpa.defer-datasource-initialization=true